export default [
  {
    id: "1",
    title: "Assignment 17",
    requested: "Today by 3:00PM",
    Due: "07/01/2021",
    teacher: "Brendese",
    grade: "11th",
    progress: "Complete",
  },
  {
    id: "2",
    title: "Importance of Voting",
    requested: "Yesterday by 1:00PM",
    Due: "06/04/2021",
    teacher: "Gerbini",
    grade: "11th",
    progress: "1 more hour",
  },
  {
    id: "3",
    title: "Macromolecules Assignment",
    requested: "Today by 10:00AM",
    Due: "07/04/2021",
    teacher: "Ausfeld",
    grade: "11th",
    progress: "Not Started",
  },
  {
    id: "4",
    title: "Golf Form",
    requested: "Today by 3:00PM",
    Due: "06/02/2021",
    grade: "11th",
    teacher: "Kinder",
    progress: " Soon",
  },
];
